services:
  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - ticket-service
      - event-service

  ticket-service:
    build: ./backend/ticket-service
    ports:
      - "8091:8091"

  event-service:
    build: ./backend/event-service
    ports:
      - "8092:8092"
