services:
  keycloak-db:
    image: postgres:16.1
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5543:5432"
    volumes:
      - ./infrastructure/keycloak/db:/var/lib/postgresql/data
    networks:
      - skeleton_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev # --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    #    volumes:
    #      - ./infrastructure/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    depends_on:
      - keycloak-db
    networks:
      - skeleton_net

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - ticket-service
      - event-service
    networks:
      - skeleton_net

  ticket-service:
    build: ./backend/ticket-service
    ports:
      - "8091:8091"
    networks:
      - skeleton_net

  event-service:
    build: ./backend/event-service
    ports:
      - "8092:8092"
    networks:
      - skeleton_net

volumes:
  postgres_data:

networks:
  skeleton_net:
    driver: bridge
