version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - ticket-service
      - event-service

  ticket-service:
    build: ./ticket-service
    ports:
      - "8091:8091"

  event-service:
    build: ./event-service
    ports:
      - "8092:8092"
