gateway:
  url: http://api-gateway:8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9090/realms/skeleton
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: ${CLIENT_SECRET}  #.env file
            scope: openid,profile,email
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://host.docker.internal:9090/realms/skeleton
