spring:
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: http://ticket-service:8091
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=1

        - id: event-service
          uri: http://event-service:8092
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1