gateway:
  url: http://localhost:8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/skeleton
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ticket-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1